inherit_from: .rails-rubocop.yml

AllCops:
  Exclude:
    - 'test/dummy/**/*'
    - 'lib/super_hero.rb'
    - 'lib/super_hero/**/*'

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
